# database.yml
development:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: huzaifa
  password: 1234
  database: memee_dev

test:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: huzaifa
  password: 1234
  database: memee_test

production:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: deploy
  password: admin123

  database: memee-production

staging:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: deploy
  password: admin123
  database: memee-staging
