name: Deploy Rails App

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . -t ror:latest

      - name: Run Docker container
        run: |
          docker run --name ror-dep -d -e DATABASE_USERNAME=huzaifa -e DATABASE_PASSWORD=1234 -e DATABASE_NAME=memee_dev -e DATABASE_NAME=memee_test -p 8000:3000 ror:latest

      - name: Wait for the PostgreSQL service to be available 
        run: |
          sleep 10
          until docker exec ror psql -U huzaifa -d memee_dev memee-test -c '\q'; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5 
          done

      - name: Create Database and run migrations
        run: |
          docker exec ror-dep rails db:create 
          docker exec ror-dep rails db:migrate

      - name: Clean up
        run: |
          docker stop ror-dep
          docker rm ror-dep
        
