name: Build, Setup DB and Migrate

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ror:latest .

    - name: Remove existing container (if any)
      run: |
        sudo docker stop ror-dep || true
        sudo docker rm ror-dep || true

    - name: Run Docker container
      run: |
        sudo docker run -d --name ror-dep -p 8000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/ror:latest

    - name: Set up PostgreSQL user and databases
      run: |
        sudo docker exec ror-dep psql -U postgres -c "CREATE USER huzaifa WITH PASSWORD '1234';"
        sudo docker exec ror-dep psql -U postgres -c "CREATE DATABASE memee_dev OWNER huzaifa;"
        sudo docker exec ror-dep psql -U postgres -c "CREATE DATABASE memee_test OWNER huzaifa;"

    - name: Run Rails database migration
      run: |
        sudo docker exec ror-dep bundle exec rails db:migrate
