name: Build, Setup DB, and Migrate

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ror:latest .

    - name: Remove existing container (if any)
      run: |
        docker stop ror-dep || true
        docker rm ror-dep || true

    - name: Run Docker container
      run: |
        docker run -d --name ror-dep -p 8000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/ror:latest

    - name: Wait for PostgreSQL to start
      run: |
        sleep 10  # Wait for PostgreSQL to fully start up in the container

    - name: Set up PostgreSQL user and databases
      run: |
        docker exec -i ror-dep psql -U postgres -c "CREATE USER huzaifa WITH PASSWORD '1234';"
        docker exec -i ror-dep psql -U postgres -c "CREATE DATABASE memee_dev OWNER huzaifa;"
        docker exec -i ror-dep psql -U postgres -c "CREATE DATABASE memee_test OWNER huzaifa;"

    - name: Run Rails database migration
      run: |
        docker exec -i ror-dep bundle exec rails db:migrate

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ror:latest
